---
abstract: ~
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Moose: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lamborghini-Web
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Request::Upload: 0
  Catalyst::Runtime: 0
  Config::General: 0
  DBIx::Class: 0
  DateTime: 0
  Email::Valid: 0
  File::MimeInfo::Magic: 0
  List::MoreUtils: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Types::Moose: 0
  MooseX::Types::URI: 0
  Net::DNS: 0
  Net::Domain::TLD: 0
  Regexp::Common: 0
  namespace::autoclean: 0
version: 0.01
